# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Define American Summit 2019"
email: "info@defineamerican.com"
description: "The largest convening on American identity"
baseurl: "/zeppelin"
url: "https://gdg-x.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Define American"
organizerAlternateName: "Define American Summit"
organizerDescription: "Define American is a nonprofit media and culture organization that uses the power of story to transcend politics and shift the conversation about immigrants, identity, and citizenship in a changing America."
organizerEmail: "info@defineamerican.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://defineamerican.com/"

# Head
metaKeywords: "event, Define American, immigration, identity, summit, Louisville, Kentucky"
twitterAccount: "@DefineAmerican"
socialImageSrcLinkedIn: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "assets/Chapters Summit - 2019 Sponsorship Packet DRAFT 053019.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 # - {permalink: "https://www.eventbrite.com/e/define-american-summit-tickets-67633819575", text: "Tickets"}
 - {permalink: "/logistics/", text: "Getting there"}
bottomNavigationLinks:
 - {link: "https://www.eventbrite.com/e/define-american-summit-tickets-67633819575", text: "Get Tickets"}
rightNavigationButtons:
 - {link: "https://www.eventbrite.com/e/define-american-summit-tickets-67633819575", text: "Get Tickets"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Define American Summit <typeout>  2019"
eventDate: "October 10-13, 2019"
typeoutTextValues: '"Culture", "Immigration", "Identity", "Race"'
typeoutFallback: "Louisville"
heroButtons:
 - {link: "https://www.eventbrite.com/e/define-american-summit-tickets-67633819575", text: "Get tickets"}

# About Block
aboutTitle: "Join us in Louisville"
aboutBlock:
 - {title: "Summit", image: "conference.jpg", text: "The largest convening ever on American identity!" }
 - {title: "Workshops", image: "hackathon.jpg", text: "2.5 days of workshops, plenaries, difficult conversations, and hands-on training." }
 - {title: "Culture", image: "workshop.jpg", text: "Culture change in action with stand-up comedy, cultural festival, and culture change dialogue." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "72", specialCharacter: "+", info: "hours", detail: "of pure culture change strategy and tactics"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from across the nation and the political spectrum"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus culture & entertainment"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Dynamic speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Summit Venue"
eventLocationName: "GALT House Hotel"
eventLocationLink: "https://www.galthouse.com/"
eventStreetAddress: "140 N Fourth St"
eventAddressLocality: "Louisville"
eventAddressLocalityRegion: "Kentucky"
eventPostalCode: "40202"
eventAddressCountry: "USA"
# eventStartTime: "2019-10-10T5:00"
# eventDoorTime: "05:00"
# eventEndTime: "2019-10-13T1:00"
eventPlaceCoordinates: "38.2581251,-85.7593204"
mapCenterCoordinates: "38.2581251,-85.7593204"
mapMobileCenterCoordinates: "38.2581251,-85.75932041"

# Venue Block
venueBlockTitle: "Opening Night Reception"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Muhammad Ali Center"
venueFeatures: ["140 N. 6th St.","Red Carpet & Step & Repeat Backdrop", "Live DJ + Promigra Hip Hop", "Chapters Video Award"]

#Comedy Night Block
comedyBlockTitle: "Comedy Night"
comedyBigImage: "comedy_0.png"
comedySmallImage1: "comedy_1.png"
comedySmallImage2: "comedy_2.jpg"
comedySmallImage3: "comedy_3.jpg"
comedyTitle: "Mercury Ballroom"
comedyFeatures: ["Culture Changing Comedians", "611 S 4th St", "Felonius Monk","Zahra Noorbakhsh"]
comedyButtons:
 - {link: "https://www.universe.com/events/define-american-summit-comedy-night-tickets-RL2CVY", text: "Get Comedy Night tickets"}

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "DAsummit"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Early bird prices"
ticketsInfo: "General admission tickets grant access to all summit sections, coffee breaks, lunch and parties. Accommodation is NOT included in the ticket price. A la carte tickets also available at ticketing link."
ticketsOffers:
 -
  name: "General Admission"
  price: "200"
  priceCurrency: "USD"
  ticketsNumber: "150"
  ribbon: "-33%"
  buyButtonLink: "https://www.eventbrite.com/e/define-american-summit-tickets-67633819575"
  buyButtonText: "Buy Now"
  ticketContentList: ["Full summit", "General admission", "Ticket price going up soon"]
  validFrom: "2019-07-01T10:00"
  validThrough: "2019-09-1T23:59"
 -
  name: "Chapter Member"
  price: "50"
  priceCurrency: "USD"
  ticketsNumber: "100"
  ribbon: "-50%"
  featured: true
  buyButtonLink: "https://www.eventbrite.com/e/define-american-summit-tickets-67633819575"
  buyButtonText: "Buy Now"
  ticketContentList: ["Full entry for chapter members", "Eat. Drink. Learn. Teach.", "Get your tix today!"]
  validFrom: "2019-07-01T10:00"
  validThrough: "2019-09-1T23:59"
  disabled: false
 -
  name: "Student"
  price: "75"
  priceCurrency: "USD"
  ticketsNumber: "50"
  ribbon: "-50%"
  buyButtonLink: "https://www.eventbrite.com/e/define-american-summit-tickets-67633819575"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in."
  ticketContentList: ["All students welcome!", "Learn about Define American Chapters.", "Buy ticket today!"]
  validFrom: "2019-07-01T10:000"
  validThrough: "2019-09-1T23:59"
  # soldOut: true
  # soldOutText: "Available"

# Footer
socialLinks:
 - {link: "https://www.linkedin.com/company/defineamerican/", icon: "linked-in"}
 - {link: "https://twitter.com/DefineAmerican", icon: "twitter"}
 - {link: "https://facebook.com/DefineAmerican", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://defineamerican.com", text: "defineamerican.com"}
 -
  title: "Contact"
  links:
   - {link: "mailto:info@defineamerican.com", text: "info@defineamerican.com"}
 #-
 # title: "FAQ"
 # links:
 #  - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest Summit news"
blogCommentsEnabled: false
discusShortName: "dasummit"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Define American is a nonprofit media and culture organization that uses the power of story to transcend politics and shift the conversation about immigrants, identity, and citizenship in a changing America."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "38.2581251,-85.7593204"
logisticsMapMobileCenterCoordinates: "38.2581251,-85.7593204"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Louisville"
directionDetailsCards:
 - {title: "From the Louisville International Airport (SDF)", information: 'The airport is due south of the city center. It is easily reachable by car, public transport or taxi. More information is available at <a href="https://www.flylouisville.com/">airport website</a>.'}
 - {title: "Airport shuttle", information: 'Shuttle service from the airport can be reserved for a charge to the Galt House Hotel. Shuttle departs at quarter of and quarter to, from 7:15 am through 11:45 pm. $15 per one-way trip, or $25 per round trip. <br /><em>To reserve</em>: To reserve your seat on a shuttle, please contact Xtreme Transportation at (502) 561-4022 or galthouseshuttle@xtlimo.com. <br />Lyft and Uber services are readily available at the Louisville airport.'}
 - {title: "Accomodations", information: 'The Summit hotel is the <a href="https://www.galthouse.com/">Galt House Hotel</a>. In order to make reservations in our group block, visit <a href="https://book.passkey.com/event/49963226/owner/817279/home">our hotel booking page</a>. The group rate of $159/night will expire on September 20, 2019.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotel"
    links:
     - {link: "https://www.galthouse.com/", text: "Galt House Hotel"}
   -
    title: "Summit Registration"
    links:
     - {link: "https://www.eventbrite.com/e/define-american-summit-tickets-67633819575", text: "Get Summit Tickets"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
